### ISSUE TITLE
Issue Building ENDFtk dev branch  

### ISSUE THREAD

**Issue by mcornock** [njoy/ENDFtk#118]
@whaeck  There should be a text file attached to show errors raised when building with gcc-7 and clang-8
[error.txt](https://github.com/njoy/ENDFtk/files/5907286/error.txt)

**Comment by whaeck** [comment]
I can now confirm the g++-7 issue: we also get an internal compiler error when using github actions on ubuntu 18.04. 'm going to do a few tests on other systems to see if it is a general issue.

**Comment by jkulesza** [comment]
Could this be a memory-use issue?  

During compile, I'm seeing >4GB memory used with even a single threaded compile (e.g., while compiling `Tape`).  I ran across a similar failure while building in a Docker image provisioned with only a fraction of the full system memory.  

Note that Gitlab CI/CD Docker images are limited at 4GB, so this will be prohibitive there.  I'm unsure about any Github Actions limitation(s).

**Comment by whaeck** [comment]
It might be. We do know ENDFtk compilation is memory intensive - probably because of the heavy template usage in ranges, hana, etc. The resonance reconstruction library is even worse: memory peaks at over 10GB in that one. The compilation time using g++ for that one also becomes outrageously large (almost an hour for certain unit tests).

I'm not surprised this happens when compiling Tape or Material since these components need the entirety of ENDFtk to compile. We've added compiler guards in the past so that smaller pieces of ENDFtk can be included instead of having to include everything every single time. For something like the python bindings, with a large number of cpp files where we bind small pieces, this saves a lot in compile time but it does not solve the memory issue for the ones that need almost everything like Tape and Material.

We may want to reimplement certain pieces of ENDFtk when and if we can figure out exactly what causes the high memory consumption during compilation. Another solution is to move to precompilation of the library prior to inclusion in other projects.

The Github action runners are limited to 7 GB of memory for the windows/linux runners and 14 GB for the MacOS runners (just looked it up here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

**Comment by whaeck** [comment]
@mcornock We now have a new branch of ENDFtk in which I've updated the range/v3 library to the latest release version. I have tried it with g++-9 and g++-10 and it compiles just fine while with the latest develop branch, g++-9 fails. I'm trying g++-7 and g++-8 now.

@jkulesza This latest branch has a peak memory consumption for Tape of 2.5 GB. I don't know what it used to be, but this number is definately lower than the 4GB you reported.

Give it a try, the name of the branch is update/ranges

**Comment by jkulesza** [comment]
> This latest branch has a peak memory consumption for Tape of 2.5 GB. I don't know what it used to be, but this number is definately lower than the 4GB you reported.

Thanks for posting this.  I've had weird, mixed, success.  I'll compile a list of successful/failing configurations and post it.  However, I wanted to provide status here to ensure you know there is continuing interest/effort from this side.

**Comment by whaeck** [comment]
@jkulesza Let's talk about this when you have some time.
