### ISSUE TITLE
Problems with one of the constructors (copy?)

### ISSUE THREAD

**Issue by jlconlin** [njoy/ENDFtk#71]
The following compiles, but gives a `SIGABRT` when run
```cpp
struct make{
  using Tape_t = syntaxTree::Tape< std::string >;
  using Format_t = std::variant< Tape_t >;

  static
  Format_t makeTape(){
    std::string tapeString{/*something here*/};
    Tape_t tape{ std::move( tapeString ) };
    return tape;
    }
};

auto evaluated = make::makeTape();
```

I'm not sure, but I think there is something wrong with with one of the constructors. 

The problem lies in creating the `Tape_t` object and then "converting" it to the `Format_t` (`std::variant`). An alternative implementation of `makeTape`, that doesn't cause a `SIGABRT` is:

```cpp
static
Format_t makeTape(){
  std::string tapeString{/*something here*/};
  Format_t tape{ std::move( tapeString ) };
  return tape;
}
```

I think (but not sure) that this indicates a problem with the copy or move constructor.

**Comment by whaeck** [comment]
I figured out what this one is about. It's the move constructor on the Tape that is broken. I had this happen to me as well.

In the current implementation, the tape identification is considered optional. Why that choice was made, I don't know (I've never seen an ENDF tape file without the tape ID). As a result, when a tape is moved, the code needs to take into account the possibility of that tape ID not being there when the new tape indexes the buffer that was moved over. There's even a private intermediate move constructor because of this. Whenever the move constructor is called (which happens in your first example when you pass the move out of the function), the code seems to try and figure out if there was a tape ID by comparing the begin iterator of the buffer with the begin iterator of the first material in the original tape. It then uses the result of that comparison to either move the materials or index the buffer again.

The sigabort seems to occur due to an assertion failure in the ranges library (when using ranges::distance on those iterators).

If we take away the optional nature of the tape identifier, and thus require it to be there (which appears to be the case in all physical ENDF files I have ever seen), then the code can be simplified accordingly (we can even rely on the compiler generated move constructor - I think).

**Comment by whaeck** [comment]
So it's even easier than that.

The move constructor moves the **Buffer** from the tape when calling the private intermediate move constructor, while the private intermediate move constructor expects a moved **Tape**. Moving the tape instead of the buffer fixes the issue.
